export const ADD_TASK = "ADD_TASK";
export const SET_ACTIVE_LIST_ID = "SET_ACTIVE_LIST_ID";
export const ADD_LIST = "ADD_LIST";
export const SET_TASK_INTO_LIST = "SET_TASK_INTO_LIST";
export const SET_TASK_IMPORTANT = "SET_TASK_IMPORTANT";
export const SET_TASK_STATUS = "SET_TASK_STATUS";
